Repository nextcloud-snap/nextcloud-snap, pull requests merged in 2023-08, with the labels that each got.

#2487 Upgrade PHP to 8.1.22
  snap/snapcraft.yaml
Labels: security

#2483 tests: support newer chrome version
  tests/.ruby-version
  tests/Gemfile
  tests/Gemfile.lock
  tests/integration/spec_helper.rb
Labels: 25

#2484 tests: support newer chrome version
  tests/.ruby-version
  tests/Gemfile
  tests/Gemfile.lock
  tests/integration/spec_helper.rb
Labels: 26

#2476 Update: MySQL to 8.0.34
  snap/snapcraft.yaml
Labels: 25

#2474 nextcloud: upgrade to 25.0.9
  snap/snapcraft.yaml
Labels: 25

#2489 Upgrade PHP to 8.1.22
  snap/snapcraft.yaml
Labels: 25

#2500 Release 25.0.9snap1
  CHANGELOG
Labels: 25

#2496 nextcloud: update to 26.0.5
  snap/snapcraft.yaml
Labels: 26

#2498 nextcloud: update to 25.0.10
  snap/snapcraft.yaml
Labels: 25
