Repository nextcloud-snap/nextcloud-snap, pull requests merged in 2023-10, with the labels that each got.

#2551 CI: upload snap artifact
  .github/workflows/test.yml
Labels: 26

#2547 nextcloud: enable theming by default
  src/nextcloud/fixes/fresh-install/1_disable-theming.sh
Labels: 26

#2554 CI: upload snap artifact
  .github/workflows/test.yml
Labels: 25

#2548 nextcloud: update to 26.0.7
  snap/snapcraft.yaml
Labels: 26

#2550 nextcloud: update to 25.0.12
  snap/snapcraft.yaml
Labels: 25

#2572 Upgrade Apache to 2.4.58
  snap/snapcraft.yaml
Labels: security

#2574 Upgraded Redis to 6.2.14
  snap/snapcraft.yaml
Labels: security

#2566 release 25.0.12snap1
  CHANGELOG
Labels: 25

#2565 release 26.0.7snap1
  CHANGELOG
Labels: 26

#2575 Upgrade Apache to 2.4.58
  snap/snapcraft.yaml
Labels: 25

#2576 Upgrade Apache to 2.4.58
  snap/snapcraft.yaml
Labels: 26

#2577 Upgraded Redis to 6.2.14
  snap/snapcraft.yaml
Labels: 26

#2578 Upgraded Redis to 6.2.14
  snap/snapcraft.yaml
Labels: 25

#2581 apache: use archive site instead of dlcdn
  snap/snapcraft.yaml
Labels: 26

#2582 apache: use archive site instead of dlcdn
  snap/snapcraft.yaml
Labels: 25

#2590 Upgrade MySQL to 8.0.35
  snap/snapcraft.yaml
Labels: 26

#2591 Upgrade MySQL to 8.0.35
  snap/snapcraft.yaml
Labels: 25

#2595 nextcloud: update to 26.0.8
  snap/snapcraft.yaml
Labels: 26

#2596 nextcloud: update to 25.0.13
  snap/snapcraft.yaml
Labels: 25
