Repository nextcloud-snap/nextcloud-snap, pull requests merged in 2023-09, with the labels that each got.

#2514 snapcraft.yaml: remove mdns-publisher
  README.md
  snap/snapcraft.yaml
Labels: 24

#2525 nextcloud: update to 25.0.11
  snap/snapcraft.yaml
Labels: 25

#2526 nextcloud: update to 26.0.6
  snap/snapcraft.yaml
Labels: 26

#2531 mysql: revert commit be8348a7c3
  snap/snapcraft.yaml
  src/patches/mysql-revert-BUG-34849343-Aligned_atomic-not-working-as-in.patch
Labels: 26

#2539 CHANGELOG: update for 26.0.6snap1
  CHANGELOG
Labels: 26

#2540 CHANGELOG: update for 25.0.11snap1
  CHANGELOG
Labels: 25
