Repository nextcloud-snap/nextcloud-snap, pull requests merged in 2023-07, with the labels that each got.

#2447 snapcraft.yaml: remove mdns-publisher
  README.md
  snap/snapcraft.yaml
Labels: 25

#2449 Upgrade Redis to 6.2.13
  snap/snapcraft.yaml
Labels: dependency, security

#2463 Update: MySQL to 8.0.34
  snap/snapcraft.yaml
Labels: security

#2465 Update: Nextcloud to 26.0.4
  snap/snapcraft.yaml
Labels: 26

#2454 Release 25.0.8snap1
  CHANGELOG
Labels: 25

#2475 Upgrade Redis to 6.2.13
  snap/snapcraft.yaml
Labels: 25
